---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host1
spec:
  storageClassName: "local"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host2
spec:
  storageClassName: "local"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/vol2"