kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-host
  labels:
    type: host
spec:
  storageClassName: "local"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi